#!/bin/sh

######## CONFIGURATION OPTIONS ########
## Full path to Exaile bin dir
#PROGRAM_DIR="/home/username/apps/exaile"
## Python command to run
#PYTHON3=python3
#######################################

# get the app dir if not already defined
if [ -z "${PROGRAM_DIR}" ]; then
    PROGRAM_DIR=`dirname "$0"`
fi

if [ -z "${PYTHON3}" ]; then
    PYTHON3=python3
fi

exec ${PYTHON3} -O ${PROGRAM_DIR}/exaile.py --startgui "$@"
