#!/bin/sh

######## CONFIGURATION OPTIONS ########
## Full path to Exaile bin dir
#PROGRAM_DIR="/home/username/apps/exaile"
## Python command to run
#PYTHON2=python2
#######################################

# get the app dir if not already defined
if [ -z "${PROGRAM_DIR}" ]; then
    PROGRAM_DIR=`dirname "$0"`
fi

if [ -z "${PYTHON3}" ]; then
    if [ "`which python3 2> /dev/null`" ]; then
        PYTHON2=python3
    else
        PYTHON2=python
    fi
fi

exec ${PYTHON3} -O ${PROGRAM_DIR}/exaile.py --startgui "$@"
