#!/bin/sh

######## CONFIGURATION OPTIONS ########
## Full path to Exaile bin dir
#PROGRAM_DIR="/home/username/apps/exaile"
## Python command to run
#PYTHON=python2
#######################################

# get the app dir if not already defined
if [ -z "$PROGRAM_DIR" ]; then
    PROGRAM_DIR=`dirname "$0"`
fi

if [ -z "$PYTHON" ]; then
    if [[ `which python2 2> /dev/null` ]]; then
        PYTHON=python2
    else
        PYTHON=python
    fi
fi

exec $PYTHON -O ${PROGRAM_DIR}/exaile.py --startgui "$@"
