.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH EXAILE 1 "October 16, 2006"
.SH NAME
exaile \- an AmaroK-like media player
.SH SYNOPSIS
.B exaile
.RI [options]
.SH DESCRIPTION
.B Exaile
is a media player aiming to be similar to KDE's AmaroK, but for
GTK+. It incorporates many of the cool things from AmaroK (and other media
players) like automatic fetching of album art, handling of large libraries,
lyrics fetching, artist/album information via the wikipedia, last.fm
support, optional iPod support (assuming you have python-gpod installed).
 
.SH OPTIONS
.TP
.B \-h, \-\-help
Show summary of options and exit
.TP
.B \-d DIR, \-\-duplicates=DIR
Finds and deletes all duplicate tracks (based on their md5 sum)
.TP
.B \-n, \-\-next
Play the next track
.TP
.B \-p, \-\-prev
Play the previous track
.TP
.B \-s, \-\-stop
Stop playback
.TP
.B \-a, \-\-play
Play
.TP
.B \-a, \-\-play\-pause
Play/Pause Playback
.TP
.B \-a, \-\-play\-cd
Play A CD
.TP
.B \-q, \-\-query
Query player
.TP
.B \-\-gui\-query
Show a popup of the currently playing track
.TP
.B \-\-get\-title
Print the title of current track
.TP
.B \-\-get\-album
Print the album of current track
.TP
.B \-\-get\-artist
Print the artist of current track
.TP
.B \-\-get\-length
Print the length of current track
.TP
.B \-\-current\-position
Print the position inside the current track as a percentage
.TP
.B \-i VOL, \-\-increase_vol=VOL
Increases the volume by VOL
.TP
.B \-l VOL, \-\-decrease_vol=VOL
Decreases the volume by VOL
.TP
.B \-\-stream=URL
Stream URL
.TP
.B \-\-new
Start new instance
.TP
.B \-\-settings=SETTING
Settings Directory

.SH SEE ALSO
More information is available on the
.B exaile
web page:
.IR http://www.exaile.org
.SH AUTHOR
.B Exaile
was written by Adam Olsen <arolsen@gmail.com>
.P
This manual page was written by Fran\[,c]ois F\['e]votte <francois.fevotte@ensta.org>
