"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import os
import os.path
import sys
from setuptools import setup
import py2app

os.chdir(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))

packages = ['xl', 'xlgui']

APP = ['exaile.py']
DATA_FILES = ['data', 'plugins']
OPTIONS = {'argv_emulation': True,
           'dist_dir': 'tools/osx/Exaile',
           'iconfile': 'data/images/exaile.icns',
           'packages': packages}

# this is a hack
sys.argv.append('--bdist-base')
sys.argv.append('tools/osx/build')
sys.argv.append('--argv-inject')
sys.argv.append('--startgui')

# sum up all the packages
#packages = ['plugins']
# for root, dirs, files in os.walk("../../plugins"):
#    for fname in files:
##        pkg = '.'.join(root.split('/')[2:])
#        if fname == '__init__.py' and pkg != 'plugins':
#            packages.append(pkg)

setup(
    app=APP,
    data_files=DATA_FILES,
    name='Exaile',
    license='GPL',
    url='http://www.exaile.org',
    version='3.4',
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
