#!/usr/bin/env python

import sys, os

sys.path.append(os.getcwd())

from IPython.Shell import IPShellEmbed
from xl import main

exaile = main.Exaile()

ipshell = IPShellEmbed(user_ns=dict(exaile=exaile))
ipshell()
