#!/bin/sh

#TODO: is tere a better way to do this?
ROOT=
PROG=
ARGS=
for arg in "$@"; do
    if [ -z $ROOT ]; then
        ROOT=$arg
    else 
        if [ -z $PROG ]; then
            PROG=$arg
        else
            ARGS="$ARGS $arg"
        fi
    fi
done

echo $ROOT
echo $PROG
echo $ARGS

XDG_CONFIG_HOME=$ROOT/config/ XDG_DATA_HOME=$ROOT/data/ XDG_CACHE_HOME=$ROOT/cache/ $PROG $ARGS
