#!/bin/sh

if [ $# -lt 2 ]; then
    echo "Usage: $0 prefix command [args...]"
    exit 1
fi

PREFIX=$1
CMD=$2
shift 2

export XDG_CONFIG_HOME="$PREFIX/config/"
export XDG_DATA_HOME="$PREFIX/data/"
export XDG_CACHE_HOME="$PREFIX/cache/"

exec "$CMD" "$@"
