#!/usr/bin/env python
"""This file is automatically generated by generate_version_info
It uses the current working tree to determine the revision.
So don't edit it. :)
"""

version_info = {'branch_nick': u'exaile',
 'build_date': '2008-02-06 08:24:29 -0700',
 'clean': None,
 'date': '2008-02-06 08:09:27 -0700',
 'revision_id': 'arolsen@gmail.com-20080206150927-trtc1ro09919kxpw',
 'revno': 1522}

revisions = {}

file_revisions = {}



if __name__ == '__main__':
    print 'revision: %(revno)d' % version_info
    print 'nick: %(branch_nick)s' % version_info
    print 'revision id: %(revision_id)s' % version_info
