#!/usr/bin/env python
"""This file is automatically generated by generate_version_info
It uses the current working tree to determine the revision.
So don't edit it. :)
"""

version_info = {'branch_nick': u'main',
 'build_date': '2008-07-03 13:32:56 -0500',
 'clean': None,
 'date': '2008-06-30 12:16:09 -0500',
 'revision_id': 'reacocard@gmail.com-20080630171609-x7efbfgyl1acpaj4',
 'revno': 1643}

revisions = {}

file_revisions = {}



if __name__ == '__main__':
    print 'revision: %(revno)d' % version_info
    print 'nick: %(branch_nick)s' % version_info
    print 'revision id: %(revision_id)s' % version_info
