#!/usr/bin/env python
"""This file is automatically generated by generate_version_info
It uses the current working tree to determine the revision.
So don't edit it. :)
"""

version_info = {'branch_nick': u'main',
 'build_date': '2008-06-28 19:13:42 -0500',
 'clean': None,
 'date': '2008-06-22 15:51:27 +0200',
 'revision_id': 'info@noctus.net-20080622135127-ef1r3ogxzwz6rqwm',
 'revno': 1641}

revisions = {}

file_revisions = {}



if __name__ == '__main__':
    print 'revision: %(revno)d' % version_info
    print 'nick: %(branch_nick)s' % version_info
    print 'revision id: %(revision_id)s' % version_info
